[workspace]

[package]
name = "sp1-guest"
version = "0.1.0"
edition = "2021"


# deprecated binary target for ontake fork block processing
# [[bin]]
# name = "sp1-block"
# path = "src/block.rs"

[[bin]]
name = "sp1-aggregation"
path = "src/aggregation.rs"

[[bin]]
name = "sp1-batch"
path = "src/batch.rs"

[[bin]]
name = "sp1-shasta-aggregation"
path = "src/shasta_aggregation.rs"

# [[test]]
# name = "main"
# path = "src/main.rs"
# harness = false

[dependencies]
raiko-lib = { path = "../../../lib", features = ["std", "sp1"] }
sp1-zkvm = { version = "6.0.0", features = ["verify"] }
sp1-primitives = { version = "6.0.0", default-features = false }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.8-sp1-6.0.0" }
harness-core = { path = "../../../harness/core" }
harness = { path = "../../../harness/macro", features = ["sp1"] }
substrate-bn = { git = "https://github.com/sp1-patches/bn", package = "substrate-bn-succinct-rs", tag = "patch-0.6.0-sp1-6.0.0" }


bincode = "1.3.3"
lazy_static = "1.5.0"
num-bigint = { version = "0.4.6", default-features = false }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-6.0.0" }

# Explicitly adding c-kzg with feature eip-7594 to fix 
# error[E0599]: no method named `compute_cells_and_kzg_proofs` found for reference `&KzgSettings` in the current scope
# in alloy-eips
c-kzg = { git = "https://github.com/risc0/c-kzg-4844", tag = "v2.1.5-risczero.0", features = [
    "eip-7594",
] }

[patch.crates-io]
c-kzg = { git = "https://github.com/risc0/c-kzg-4844", tag = "v2.1.5-risczero.0" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.8-sp1-6.0.0" }
sha3-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha3", tag = "patch-sha3-0.10.8-sp1-6.0.0" }
crypto-bigint = { git = "https://github.com/sp1-patches/RustCrypto-bigint", tag = "patch-0.5.5-sp1-6.0.0" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-6.0.0" }
substrate-bn = { git = "https://github.com/sp1-patches/bn", package = "substrate-bn-succinct-rs", tag = "patch-0.6.0-sp1-6.0.0" }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-6.0.0" }
p256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-p256-13.2-sp1-6.0.0" }
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.30.0-sp1-6.0.0" }

[features]
default = ["sp1-cycle-tracker"]
sp1-cycle-tracker = ["raiko-lib/sp1-cycle-tracker"]
